# Generated by Django 5.1.4 on 2025-01-05 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lan', to='locations.land')),
            ],
        ),
        migrations.CreateModel(
            name='Stad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stader', to='locations.lan')),
            ],
        ),
    ]
