# Generated by Django 5.1.4 on 2025-03-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForetagsStorlek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('ikon', models.CharField(blank=True, max_length=100, null=True)),
                ('farg_css_klass', models.CharField(blank=True, max_length=100, null=True)),
                ('sorteringsordning', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerksamhetsOmraden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100)),
                ('ikon', models.CharField(blank=True, max_length=100, null=True)),
                ('farg_css_klass', models.CharField(blank=True, max_length=100, null=True)),
                ('sorteringsordning', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=200)),
                ('epost', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('hemsida', models.URLField(blank=True, null=True)),
                ('kontaktperson', models.CharField(blank=True, max_length=100, null=True)),
                ('logotype', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('bild1', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('bild2', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('bild3', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('payoff', models.CharField(blank=True, max_length=300, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('kund', models.BooleanField(default=False)),
                ('underleverantor', models.BooleanField(default=False)),
                ('organisationsnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('adressrad1', models.CharField(blank=True, max_length=200, null=True)),
                ('adressrad2', models.CharField(blank=True, max_length=200, null=True)),
                ('adressrad3', models.CharField(blank=True, max_length=200, null=True)),
                ('betald', models.BooleanField(default=False)),
                ('betald_datum', models.DateField(blank=True, null=True)),
                ('betalning_utgangsdatum', models.DateField(blank=True, null=True)),
                ('uppdaterad_datum', models.DateTimeField(auto_now=True)),
                ('boost', models.BooleanField(default=False)),
                ('super_boost', models.BooleanField(default=False)),
                ('boost_startdatum', models.DateTimeField(blank=True, null=True)),
                ('boost_slutdatum', models.DateTimeField(blank=True, null=True)),
                ('verksamma_lander', models.ManyToManyField(blank=True, to='locations.land')),
                ('verksamma_stader', models.ManyToManyField(blank=True, to='locations.stad')),
                ('storlek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.foretagsstorlek')),
                ('omraden', models.ManyToManyField(blank=True, to='companies.verksamhetsomraden')),
            ],
        ),
    ]
