# Generated by Django 5.1.4 on 2025-03-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adressrad1',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='company',
            name='adressrad2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='adressrad3',
        ),
        migrations.RemoveField(
            model_name='company',
            name='bild2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='bild3',
        ),
        migrations.RemoveField(
            model_name='company',
            name='text3',
        ),
        migrations.AddField(
            model_name='company',
            name='kategoriBransch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='konkurs',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_numbers', to='companies.company')),
                ('omrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_numbers', to='companies.verksamhetsomraden')),
            ],
        ),
    ]
